### ISSUE TITLE
immediate crash on pressing droplet "settings" button

### ISSUE THREAD

**Issue by phloggu** [sveinbjornt/Platypus#87] opened 2017-01-10 02:41 UTC
Pressing the button "settings" just behind "Accepts dropped items" or choosing from the menu "Advanced" -> "Edit Drop Settings..." crashes Platypus almost always. With some of the example profiles, the dialog can be opened though. It crashes with no loaded profile or at least with the profile "Spotlightinfo".

Steps to reproduce on a freshly downloaded v5.1 (887):
- open Platypus
- chose "Interface" -> "Droplet"
- click "Settings"

This is on OS X 10.9.5.

**Comment by sveinbjornt** [comment] 2017-02-24 13:18
I've been able to replicate this sometimes on 10.12. Will look into it for the 5.2 release.

**Comment by sveinbjornt** [comment] 2017-02-25 22:49
Looks like the cause was a wonky Platypus Profile example. I can't reproduce this ever since I removed old keys and added newly introduced keys to the Profile files. Closing for now, let me know if you continue experiencing this issue once 5.2 is released.

**Closed by sveinbjornt** 2017-02-25 22:49 UTC
