### ISSUE TITLE
File selection dialog always shows on launch - even when launching by dropping files

### ISSUE THREAD

**Issue by gingerbeardman** [sveinbjornt/Platypus#116] opened 2018-07-16 13:43 UTC
Similar to how [the behaviour of FastDMG has changed with a recent macOS update](https://github.com/sveinbjornt/FastDMG/issues/1), so has the behaviour of Platypus.

I have an app made with Platypus that has the following setup:
* Accepts dropped files
* Prompt for file on launch

Historically, any dropped files would take precedence over the prompt for file on launch, resulting in a very nice user experience. But right now when dropping files the prompt for file still appears.

I'm not sure why this is now happening, but given this macOS change (bug?) has affected two of your apps (and any app in the wild produced with Platypus using the above settings) I thought I would mention it.

Platypus 5.2 (1008)
macOS 10.13.5 (17F77)
current public versions

**Comment by sveinbjornt** [comment] 2018-10-02 20:45
I've been completely unable to reproduce this in Platypus and FastDMG, both on High Sierra and Mojave, on various different systems, so I can only assume that it was (is?) related to your install. Closing for now.

**Closed by sveinbjornt** 2018-10-02 20:45 UTC
