### ISSUE TITLE
Platypus not passing .webloc files

### ISSUE THREAD

**Issue by cylott** [sveinbjornt/Platypus#151] opened 2019-10-02 12:31 UTC
I'm seeing a strange issue with .webloc files. When I create an app that accepts dropped files, whatever I drag is passed as an argument, except, for some strange reason, .webloc files.

Steps to reproduce:
Create a Platypus app that accepts all dropped files
Write a script that outputs argv
Drag a .webloc file

I'm attaching an example app. All the script does is this:

`<? print_r($argv); ?>`

So, whatever I drag to it is output in the window. Except .webloc files.

[Foo.app.zip](https://github.com/sveinbjornt/Platypus/files/3681064/Foo.app.zip)

**Comment by sveinbjornt** [comment] 2019-10-02 12:55
I have managed to reproduce this, very strange indeed! Will examine.

**Comment by cylott** [comment] 2019-10-02 13:14
> I have managed to reproduce this, very strange indeed! Will examine.

At first I thought maybe a .webloc file is not covered by the UTI public.item but it appears it is

**Comment by cylott** [comment] 2019-10-15 14:29
I'm also noticing this with textClippings. When I drag a textClipping onto a window, it is not passed, but it does seem to be working by dragging onto the app icon.

**Comment by sveinbjornt** [comment] 2021-06-24 18:58
I cannot reproduce this issue on Big Sur, closing.

**Closed by sveinbjornt** 2021-06-24 18:58 UTC
