### ISSUE TITLE
"Platypus.app" is damaged and can't be opened (macOS 12.5.1)

### ISSUE THREAD

**Issue by geberl** [sveinbjornt/Platypus#232] opened 2022-09-04 09:31 UTC
Hey, congrats on the new 5.4 release.

However when I download the zip and extract the app into my Applications folder I get the following popup on opening it (also via right click):

![Screen Shot 2022-09-04 at 09 29 57](https://user-images.githubusercontent.com/7255425/188306924-9fc267ea-c4ea-4e8c-be7a-40bb38e8f533.png)

I can of course do `xattr -d com.apple.quarantine /Applications/Platypus.app` and then it opens fine. But likely this is not what you want.

In **Apparency** (https://www.mothersruin.com/software/Apparency/) the following shows up:

![Screen Shot 2022-09-04 at 09 30 12](https://user-images.githubusercontent.com/7255425/188306928-634bcd24-0708-4c11-926e-65b2facbb9d7.png)

I'm not deep into this whole notarization thing to know what this actually means though.

**Comment by RonaldPR** [comment] 2022-09-05 14:17
The same here in macOS 12.5.1 (Monterey) on M1 iMac, both when I try to run it natively or with Rosetta.
The app seems signed, but is possibly not notarized?
Version 5.3 (Intel only) still runs fine.

**Comment by sveinbjornt** [comment] 2022-09-05 16:02
I have discovered what the problem is and will be making a new release to fix it. This has to do with the signing of the Sparkle update framework. This only happens when downloading and opening 5.4, not if you upgrade Platypus 5.3 via the "Check for Updates" menu in the Application menu.

**Comment by actuallymentor** [comment] 2022-09-18 20:28
Is this related to built apps failing on non-host machines? My created app works locally but fails with a cryptic "Can't open APPNAME" error on other (M1) machines.

**Comment by Artoria2e5** [comment] 2022-09-23 03:18
For new users like me, 5.3 can be found in GitHub releases until this issue is fixed: https://github.com/sveinbjornt/Platypus/releases/tag/5.3

**Comment by Ryan-M-Smith** [comment] 2022-09-28 01:39
> For new users like me, 5.3 can be found in GitHub releases until this issue is fixed: https://github.com/sveinbjornt/Platypus/releases/tag/5.3

Thanks, this worked for me.

Also, I was able to use version 5.4 by downloading and installing version 5.3 and then upgrading to 5.4 inside the app when it prompted me. This appears to work fine, and I can open the app with no issues.

**Comment by sveinbjornt** [comment] 2022-10-22 17:02
The signing issues have been fixed in version 5.4.1.

**Closed by sveinbjornt** 2022-10-22 17:02 UTC
