### ISSUE TITLE
its a folder, not an app!

### ISSUE THREAD

**Issue by DariushMazlumi** [sveinbjornt/Platypus#101] opened 2017-08-01 14:51 UTC
hello!
^_^
I downloaded Platypus version 5.2 and I'm using a MacBook Pro Early 2015 with a 2.9 GHz Intel Core i5 processor running macOS sierra(10.12.6)(so, its 64bit and later 10.7). macOS displays platypus a folder not an app. I even copied it into Applications, nothing happened. I added a .app to it, macOS shows an error message(You can’t open the application “platypus” because it is not supported on this type of Mac). I run the Platypus.xcodeproj file and it only shows the icon (ScriptExec) in Dock.

**Comment by sveinbjornt** [comment] 2017-08-01 15:56
Downloading and running it works fine for me on several different systems and configurations. Not entirely sure what the problem is. Are you sure the archive wasn't corrupted somehow during the download process?

**Comment by DariushMazlumi** [comment] 2017-08-01 16:28
hello again!
thanks for reading my comment and answering it (:
I don't think so, but I will download it again and I attached a zipped file of that folder.
and I don't know why, but I also downloaded platypus version 4.9, it has a app inside and its working.
[platypus.zip](https://github.com/sveinbjornt/Platypus/files/1191269/platypus.zip)

**Comment by sveinbjornt** [comment] 2017-08-01 21:53
That's the Platypus source tree, not the app.

**Comment by DariushMazlumi** [comment] 2017-08-01 22:01
hello and thanks again!
I downloaded it from http://www.sveinbjorn.org/platypus  by clicking on the http://www.sveinbjorn.org/files/software/platypus.zip (Platypus Application). but its not app, its Platypus source tree.
<img width="1280" alt="screen shot 1396-05-11 at 02 25 47" src="https://user-images.githubusercontent.com/30628454/28849051-7c744a76-772a-11e7-8dc1-a0bd5fcec5d2.png">

**Comment by DariushMazlumi** [comment] 2017-08-03 15:53
hello?(:

**Comment by sveinbjornt** [comment] 2017-08-03 15:56
The download link works just fine and downloads platypus.zip, which contains the Platypus-5.2 folder, which in turn contains the Platypus application. Closing.

<img width="826" alt="screen shot 2017-08-03 at 16 55 23" src="https://user-images.githubusercontent.com/654045/28931036-b1078120-786c-11e7-814a-68015f1f2f78.png">

**Closed by sveinbjornt** 2017-08-03 15:56 UTC

**Comment by DariushMazlumi** [comment] 2017-08-04 14:29
thank you for your great app! its working!^_^
<img width="1280" alt="screen shot 1396-05-13 at 18 54 52" src="https://user-images.githubusercontent.com/30628454/28972895-a291a852-7946-11e7-905a-7540376ac5f9.png">
