### ISSUE TITLE
[Request] Apple silicon binary

### ISSUE THREAD

**Issue by andrewcrook** [sveinbjornt/Platypus#201] opened 2021-10-03 10:44 UTC
Please could you make a Apple Silicon version available?

**Comment by sveinbjornt** [comment] 2021-10-04 16:55
As soon as I release a new version, I will provide universal binaries (Intel 64-bit/Apple ARM). In the meantime, Platypus-generated apps should run well via Rosetta, seeing as how they're very lightweight.

**Comment by dqh-au** [comment] 2021-12-28 02:39
For our usecase (VICE binary distribution), it would be ideal if platypus gave us the option to choose between generating an intel, arm, or universal app. Thanks for a very useful tool by the way.

**Comment by hazcod** [comment] 2022-02-01 09:14
Was there any update on this? Thanks.

**Comment by sveinbjornt** [comment] 2022-02-02 16:31
Still haven't gotten around to releasing 5.3, which will generate Universal binaries (i.e. Intel 64bit + ARM 64bit). If people want a binary with only a single architecture, it's easy enough to run /usr/bin/strip on it.

In the meantime, it's simple enough to clone the repo and make a (Universal) build from the master branch.

**Comment by lewallen** [comment] 2022-03-07 02:42
> In the meantime, it's simple enough to clone the repo and make a (Universal) build from the master branch.

I've done this, and although the compiled app runs natively (and perfectly well), I've noticed that new applications actually made with platypus are still marked as intel applications (presumably running with Rosetta). Is there anything we can do in xcode before building to fix this? Thanks!

**Comment by hazcod** [comment] 2022-04-21 14:45
@lewallen : You need to set `ONLY_ACTIVE_ARCH` to `true` for Xcode to build the Platypus binary as arm64 too.

**Comment by gingerbeardman** [comment] 2022-06-08 16:52
No joy getting it to compile here

```
/Users/matt/Projects/Platypus/platypus_clt.build/Script-F4FB337514FBDAD500BAECEB.sh: line 3: CLT/man/cat2html/cat2html: Bad CPU type in executable
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script\ to\ Create\ Man\ Page\ HTML\ document /Users/matt/Projects/Platypus/platypus_clt.build/Script-F4FB337514FBDAD500BAECEB.sh (in target 'platypus_clt' from project 'Platypus')
(1 failure)
Build failed
```

**Comment by sveinbjornt** [comment] 2022-06-08 18:56
I'm currently working on releasing a new official build, but quality control takes time and unfortunately I don't have an arm64 Mac to test on. Hopefully I'll be able to do a release when I finally go on holiday in a couple of weeks. 

In the meantime, @gingerbeardman, the build problem you were running into has been fixed in master. For some reason, your ARM Mac (I assume?) wouldn't run the cat2html Intel binary that generates HTML from the command line tool man page. The included cat2html binary is now universal.

**Comment by gingerbeardman** [comment] 2022-06-08 19:09
Thanks!

I could maybe have gotten around that by installing Rosetta2 (to run Intel apps) but I'm going to see how long I can go without installing that. So far... 2 days!

**Comment by paulprovost** [comment] 2022-06-08 19:12
It works fine for me using Rosetta2. Just sayin'...

**Comment by gingerbeardman** [comment] 2022-06-08 19:17
Just built myself a Universal build, the unsigned version had error 65 so I just re-signed the signed version myself.

`sudo codesign -f -s - --deep Platypus.app`

👍👍

**Comment by paulprovost** [comment] 2022-06-08 22:01
> > It works fine for me using Rosetta2. Just sayin'...
> 
> Rosetta may work but its not optimised for Apple Silicon and Rosetta isn't going to be around forever.

Agreed. All I’m saying is that it’s a viable short term solution.

**Comment by Peter-Simpson** [comment] 2022-07-26 14:43
> @lewallen : You need to set `ONLY_ACTIVE_ARCH` to `true` for Xcode to build the Platypus binary as arm64 too in the build settings.

Hi ,

I'm trying to create a package for a  .NET 6 Blazor app that runs fine as an Apple Silicon executable (confirmed with the file command). I can generate a package that the system report shows as of kind "Intel" using Platypus with no issues, my difficulty is creating a package that shows up as Apple Silicon.

I'm very new to MacOS publishing and set the ONLY_ACTIVE_ARCH variable to true at the command prompt before running Platypus 5.4 from June, because I get the same build error as others have reported when cloning the current code base.

Have I missed something?

Many thanks, Peter

**Comment by andrewcrook** [comment] 2022-07-26 16:32
Hi I am not sure this is a user case for Platypus.
Platypus is used to package up command line scripts and add a GUI interface to them so they behave more like apps.

I think you are using Blazor Hybrid apps with .NET MAUI from what I can gather. This should be web tech in an executable package anyway. You just need to look at making a [DMG](https://stackoverflow.com/questions/37292756/how-to-create-a-dmg-file-for-a-app-for-mac) or if scripts need to be run upon installing a PKG both allow users to download and install your app.

I expect Microsoft has published tutorials somewhere for .Net Apps

Apple wise, If its a public app its best to code signed  and recommended to get it notarised for safe download way from Apple e.g company website. you will need an Apple Developer account. Or publish on Apple Store via a Apple Developers Account.

If it’s a company internal application use your company's MDM solution (if it has one) to distribute you can code sign using a private company key.

Testing wise you can use Test flight to share the app.

I hope that offers some areas to look into.

**Comment by andrewcrook** [comment] 2022-07-26 16:54
@Peter-Simpson 

> my difficulty is creating a package that shows up as Apple Silicon.
>...... 
> I'm very new to MacOS publishing and set the ONLY_ACTIVE_ARCH variable to true at the command prompt before  running Platypus 5.4 from June, 

Platypus isnt officially for Apple Silicon the ONLY_ACTIVE_ARCH variable is to compile Platypus from its source code using Xcode to build an Apple Silicon Version of Platypus .

**Comment by Peter-Simpson** [comment] 2022-07-26 20:12
Hi Andrew,

Thanks for your responses!

Blazor apps are console applications that expose a web server that serves an application which is accessed through a browser, and so are different from a .NET MAUI app to the best of my knowledge. 

Having investigated the generated .app file I can now see that the primary executable in the .app file is not the one I supplied, but is one that is generated by Platypus, hence it can have an architecture different from my application.

Ultimately, what I'm trying to do is to create a .app file manually, that contains a universal executable (I think I know how to create this but haven't got that far yet 😀), and where my application is the primary executable. So far, I've not been able to find a recipe for this using Apple's command line tools. 

As I said, this is my first foray into Mac development, so I'm right at the bottom of the learning curve and am having to do this without the benefits of developing the whole application in XCode. 

Best wishes, Peter

**Comment by sveinbjornt** [comment] 2022-07-26 20:17
Check out the following, @Peter-Simpson: 

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html

There's nothing magical about app bundles. It's just a directory with the .app suffix and a specific directory structure with binaries and config files.

**Comment by andrewcrook** [comment] 2022-07-27 16:18
@Peter-Simpson 

> Having investigated the generated .app file I can now see that the primary executable in the .app file is not the one I supplied, but is one that is generated by Platypus, hence it can have an architecture different from my application.

Yes that’s correct the app created by Platypus would be Intel unless you complied Platypus from source code for arm64. Platypus’s dev doesn’t have an Apple Silicon Machine that’s why it doesn’t have an Apple Silicon or universal version . The universal executable of your Blazer app will remain universal. I guess you would add a bash script so Platypus load your app then open the defualt browser to its IP and Port.  

There are tutorials out there to use Apple developer command line tools  manually I would look at submitting Rust, Java, Kaolin etc applications for code sign, notarisation and the App Store. 

- [Packaging Mac Software for Distribution](https://developer.apple.com/forums/thread/701581)
- [Creating Distribution-Signed Code for Mac](https://developer.apple.com/forums/thread/701514#701514021)
- [Signing a Mac Product For Distribution](https://developer.apple.com/forums/thread/128166)

Apparently Visual Studio 2022 can connect to a remote Mac to automate this through Xcode tools etc. It looks like you have the tools on the mac and set up SSH.

I suppose you can run Visual Studio 2022 in Parallels Windows for ARM then connect to the host macOS on the same machine. Of course, you should be able to do it straight on a Mac using Visual Studio 2022 for Mac.

[.NET MAUI macOS target publishing/archiving](https://github.com/dotnet/maui/issues/5399)
[MS document on macOS deployment](https://docs.microsoft.com/en-us/dotnet/maui/macos/deployment/overview)
[Build a Mac Catalyst app with .NET CLI](https://docs.microsoft.com/en-us/dotnet/maui/macos/cli)

Remote Mac support from Windows should be similar to this
[Pair to Mac for iOS development](https://docs.microsoft.com/en-us/dotnet/maui/ios/pair-to-mac)

However, if you look in Visual Studio 2022 look at the template for a  [.NET MAUI Blazor App ](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-6.0) this template will create an C# application which you can use  Blazor for web UI components. The template creates a project for Android, iOS/iPadOS, MacOS (Catalyst App) and Windows. You will get a native app for each platform  with a shared Blazer UI.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/2eIsQ3Pm2bE/0.jpg)](https://www.youtube.com/watch?v=2eIsQ3Pm2bE)
https://www.youtube.com/watch?v=2eIsQ3Pm2bE

**Comment by Peter-Simpson** [comment] 2022-07-29 11:26
Thanks very much @sveinbjornt and @andrewcrook for your helpful posts!

I succeeded in compiling the Platypus source as a Universal application by setting ONLY_ACTIVE_ARCH=1 and running make. I got error code 65 at the end, but the application clearly built OK. I was then able to code sign Platypus myself, and it is working as expected. The .app file Platypus created for my application now shows as Universal! 😀

Many thanks to you both and others who posted in this thread with information that helped me complete this task.

Best wishes, Peter

**Comment by mjtpena** [comment] 2022-08-29 13:38
Thank you all for the suggestion. I was able to run Platypus as universal app. I was also able to create an app that is universal (x64 and arm64) :)

**Comment by sveinbjornt** [comment] 2022-09-03 20:20
Platypus 5.4 is out w. native support for arm64: https://github.com/sveinbjornt/Platypus/releases/tag/v5.4

**Closed by sveinbjornt** 2022-09-03 20:20 UTC

**Comment by andrewcrook** [comment] 2022-09-03 21:37
@sveinbjornt  Brilliant thank you so much
